/* 
    File: main.cpp 
    Description: 11.1.1: LAB: Convert to binary - functions
    Author: Richard Grady
    Email: gradyr@student.vvc.edu
    Course#: cis202
    Section#: 30402
    Date: 04-04-2024
*/

#include <iostream>
#include <string>
using namespace std;

//This function converts in provided integer to binary via algorithm, but backward.
string IntToReverseBinary(int integerValue) {
    string binConv = "";
    while (integerValue > 0) {
        binConv += char('0' + integerValue % 2); // corrected out of range error by casting the result to a char (char in string vs int)
        integerValue = integerValue / 2;
    }
    return binConv;
}

// This function takes the string generated by the InToReverseBinary() function and reverses it.
string StringReverse(string userString) {
    string reversedString;
    int z = userString.length(); // adjust for loop with a smaller variable
    for (int i = z - 1; i >= 0; --i) {
        reversedString += userString[i];
    }
    return reversedString;
}

int main() {

    int userInput;
    cin >> userInput;

    // store the converted userInput into a variable to pass to the StringReverse function, then output.
    string result = IntToReverseBinary(userInput);
    cout << StringReverse(result);
    cout << endl;

    return 0;
}
